# Generated by Django 5.0.1 on 2024-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_classroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
