# Generated by Django 5.0.1 on 2024-03-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_person_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_name',
        ),
    ]
