# Generated by Django 5.0.1 on 2024-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_todo_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
