# Generated by Django 5.0.1 on 2024-02-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_classroom_class_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at', '-created_at']},
        ),
    ]
