# Generated by Django 5.0.1 on 2024-02-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_todo_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_date',
        ),
    ]
