# Generated by Django 5.0.1 on 2024-02-25 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_todo_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 0, 14, 17, 873367, tzinfo=datetime.timezone.utc)),
        ),
    ]
