# Generated by Django 5.0.1 on 2024-02-19 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0007_alter_classroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='first name', max_length=50)),
                ('last_name', models.CharField(default='last name', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('race', models.CharField(choices=[('Asian', 'Asian'), ('Black', 'Black'), ('White', 'White'), ('Hispanic', 'Hispanic'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user_category', models.CharField(choices=[('Student', 'Student'), ('Educator', 'Educator')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_group',
            field=models.CharField(choices=[('educators', 'educators'), ('students', 'students'), ('classroom', 'classroom'), ('subject', 'subject'), ('all', 'all')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classroom'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(to='base.subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
    ]
