# Generated by Django 5.0.1 on 2024-02-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_person_alter_classroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='base.subject'),
        ),
    ]
