# Generated by Django 5.0.1 on 2024-02-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_person_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='participants',
            field=models.ManyToManyField(blank=True, to='base.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='participants',
            field=models.ManyToManyField(blank=True, to='base.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='base.subject'),
        ),
    ]
