# Generated by Django 5.0.1 on 2024-02-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_classroom_participants_message_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.person'),
        ),
    ]
