# Generated by Django 5.0.1 on 2024-02-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_todo_is_done_alter_todo_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
    ]
