# Generated by Django 5.0.1 on 2024-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_message_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='participants',
        ),
        migrations.AddField(
            model_name='subject',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.person'),
        ),
    ]
