# Generated by Django 5.0.1 on 2024-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_student',
        ),
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('educator', 'Educator'), ('parent', 'Parent'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
