# Generated by Django 5.0.1 on 2024-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_person_is_student_person_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_group',
            field=models.CharField(choices=[('educators', 'Educators'), ('students', 'Students'), ('classroom', 'Classroom'), ('subject', 'Subject'), ('all', 'All')], default='All', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('educator', 'Educator'), ('parent', 'Parent'), ('staff', 'Staff')], default='Student', max_length=20),
        ),
    ]
